[toolchain]
anchor_version = "0.29.0"

[features]
seeds = false
skip-lint = false

[programs.mainnet]
marketplace = "3RAeCuRqF9kGXyXwk9Lynj19fuxJJj5RXCga9KiihaKF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[workspace]
members = [
    "programs/marketplace"
]

# Verification metadata
[programs.mainnet.marketplace]
address = "3RAeCuRqF9kGXyXwk9Lynj19fuxJJj5RXCga9KiihaKF"
idl = "./target/idl/marketplace.json"
