[features]
seeds = false
skip-lint = false

[programs.localnet]
marketplace = "6oN2gtocsfZ1ex6WywYrsV6o15iQoqDcqoeK96fhJRiF"
revenue_share = "FLiiRSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
token = "FLiiTKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.devnet]
marketplace = "6oN2gtocsfZ1ex6WywYrsV6o15iQoqDcqoeK96fhJRiF"
revenue_share = "FLiiRSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
token = "FLiiTKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[programs.mainnet]
marketplace = "3RAeCuRqF9kGXyXwk9Lynj19fuxJJj5RXCga9KiihaKF"
revenue_share = "FLiiRSxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
token = "FLiiTKxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[[test.genesis]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s"
program = "./deps/metadata.so"

[test.validator]
url = "https://api.devnet.solana.com"

[workspace]
members = [
    "programs/marketplace",
    "programs/revenue-share",
    "programs/token"
]
